### ISSUE TITLE
Provide snapshotting for 1.0.0 version

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#1840] opened 2018-04-10 08:40 UTC

**Comment by nazarhussain** [comment] 2018-04-10 10:03
@MaciejBaj The snapshot process is working fine with beta releases. 

```
lisk@nyc3-devnet-050:~/lisk-dev$ ./lisk_snapshot.sh

2018-04-10 09:57:45 Checking for existing snapshot operation
√ Previous snapshot is not runnning. Proceeding.

2018-04-10 09:57:45 Cleaning old snapshot instance, database and logs

2018-04-10 09:57:45 Deleting snapshots older then 7 day(s) in /home/lisk/lisk-1.0.0-beta.3-Linux-x86_64/backups

2018-04-10 09:57:45 Executing vacuum on database 'lisk_test' before copy

2018-04-10 09:57:47 Copying active database 'lisk_test' to snapshot database 'lisk_snapshot'

2018-04-10 09:57:48 Beginning snapshot verification process
√ Postgresql is running.
√ Lisk started successfully.
√ Lisk is running as PID: 11579
Current Block Height:    1862

2018-04-10 10:00:57 Executing vacuum on table 'mem_round' of database 'lisk_snapshot'
2018-04-10 10:00:58 Vacuum completed, database size: 51 MB => 38 MB

2018-04-10 10:01:58 Snapshot verification process completed

2018-04-10 10:01:58 Deleting data on table 'peers' of database 'lisk_snapshot'

2018-04-10 10:01:58 Executing vacuum on database 'lisk_snapshot' before dumping

2018-04-10 10:02:00 Dumping snapshot database to gzip file

2018-04-10 10:02:01 Cleaning up

2018-04-10 10:02:02 Snapshot Complete
```

**Comment by MaciejBaj** [comment] 2018-04-10 11:49
Please stay in touch with @Nazgolze to confirm the issue doesn't exist before closing it.

**Comment by nazarhussain** [comment] 2018-04-10 11:56
I also verified the restoring snapshot separately and counting the blocks. Also by replacing lisk instance database with snapshot and starting it again. All ways it worked. @Nazgolze We can debug it together whenever you are available.

**Comment by Nazgolze** [comment] 2018-04-10 13:46
Unable to reproduce the issue we ran into earlier. Might have been an edge case when there were very few blocks. This is working and we've been able to successfully snapshot and restore one of our seed nodes. I recommend closing this and if I'm able to reproduce it later, I'll reopen this and provide more details

**Comment by nazarhussain** [comment] 2018-04-10 13:58
@MaciejBaj We can close this issue.

**Closed** 2018-04-10 14:59 UTC
Labels: bug
