### ISSUE TITLE
balances in mem_accounts off in Betanet snapshots

### ISSUE THREAD

**Issue by webmaster128** [LiskHQ/lisk#2063] opened 2018-05-27 22:39 UTC
### Expected behavior

balances in mem_accounts should match blockchain

### Actual behavior

In Betanet snapshots (i.e. 1.0.0 snapshots), the balances in mem_accounts are off. This result is similar for every Betanet snapshot I found.

### Steps to reproduce

See this diff from a height 314507 snapshot (map `a` is the data from mem_accounts, map `b` is the calculated blockchain state). The keys are Lisk addreses without the trailing "L".

```
a[5893463983889169138] = 1655061782099; b[5893463983889169138] = 1655561584081
a[15230020972653680319] = 1617061782011; b[15230020972653680319] = 1617561683002
a[5370200325671668788] = 1522413168247; b[5370200325671668788] = 1522913168247
a[12666568332839112261] = 1625064554471; b[12666568332839112261] = 1625564455462
a[10500219976968717430] = 1395525544575; b[10500219976968717430] = 1396025445566
a[2576533421743541334] = 1527562673338; b[2576533421743541334] = 1528062574329
a[4460458459545688961] = 1666561188071; b[4460458459545688961] = 1667061089062
a[9394730630566589283] = 1592560891118; b[9394730630566589283] = 1593560792109
a[2676090374023786863] = 1541495544651; b[2676090374023786863] = 1541995445642
a[2225757506242819339] = 1653658118676; b[2225757506242819339] = 1654158019667
a[18053421712227850241] = 1397941782470; b[18053421712227850241] = 1398441584361
a[7688541383703407027] = 1582155445378; b[7688541383703407027] = 1582655346369
a[12108854850941227449] = 1537938514869; b[12108854850941227449] = 1538438415860
a[10855041329780447466] = 628975940563; b[10855041329780447466] = 628975742545
a[16425079235073154307] = 1391507326590; b[16425079235073154307] = 1392007227581
a[2091644864751040722] = 1614716237573; b[2091644864751040722] = 1615216138564
a[17905456591433106263] = 336827326720; b[17905456591433106263] = 336827227711
a[8590449891946700316] = 1590161881292; b[8590449891946700316] = 1590661782283
a[7283743314461554912] = 1524913663480; b[7283743314461554912] = 1525913663480
a[2349405299999925988] = 1593562178130; b[2349405299999925988] = 1594562079121
a[752128942908618945] = 363022277357; b[752128942908618945] = 363022178348
a[2320071442530040670] = 123518217906; b[2320071442530040670] = 124018217906
a[14538534114820652534] = 574947029712; b[14538534114820652534] = 574946930703
a[10907080765849513867] = 1541045247539; b[10907080765849513867] = 1541545148530
a[17956766617869547133] = 1532965148625; b[17956766617869547133] = 1533465049616
a[3066234107496623317] = 1655590990193; b[3066234107496623317] = 1656090891184
a[17862988679601152537] = 1533492178231; b[17862988679601152537] = 1533992079222
a[1729459574949937817] = 1596690296952; b[1729459574949937817] = 1597190197943
a[16547446877748127427] = 1598163168334; b[16547446877748127427] = 1598663069325
a[16459074898077141306] = 1533462574245; b[16459074898077141306] = 1533962475236
a[7035825815022758321] = 360209010031; b[7035825815022758321] = 360208911022
a[528628027376745866] = 1613098415755; b[528628027376745866] = 1613598316746
a[4648073518001196235] = 1603618118670; b[4648073518001196235] = 1604118019661
a[11698156576635877766] = 360633366387; b[11698156576635877766] = 360633267378
a[375276282518448358] = 1613061385993; b[375276282518448358] = 1614061286984
a[521711100687327262] = 1191090693292; b[521711100687327262] = 1191590693292
a[7737989013215138738] = 625995940590; b[7737989013215138738] = 625995841581
a[10234607838418491979] = 889089603919; b[10234607838418491979] = 889589603919
a[7856462165043403844] = 403211980425; b[7856462165043403844] = 403211881416
a[13179243681104361576] = 1541913267429; b[13179243681104361576] = 1542413267429
a[10861794177989954617] = 432049109066; b[10861794177989954617] = 432549109066
a[18128675641736923161] = 1612085742424; b[18128675641736923161] = 1612585643415
a[8296116003987221233] = 1595160792002; b[8296116003987221233] = 1596160692993
a[17466705131364624372] = 1600599901078; b[17466705131364624372] = 1601099802069
a[9599268798473959334] = 1592115445647; b[9599268798473959334] = 1592615346638
a[4093945649257196394] = 1615062277597; b[4093945649257196394] = 1615562178588
a[9972782797504924531] = 1528488217747; b[9972782797504924531] = 1528988118738
a[2040776293346035330] = 1619561980183; b[2040776293346035330] = 1620061881174
a[7072258413170632027] = 1586562871375; b[7072258413170632027] = 1587562772366
a[1436344917703966803] = 1589061980112; b[1436344917703966803] = 1589561782094
a[2193676322954236363] = 1591598811797; b[2193676322954236363] = 1592098712788
a[18144940737493947668] = 1526413861393; b[18144940737493947668] = 1526913762384
a[4425801727998563446] = 1232938019927; b[4425801727998563446] = 1233438019927
a[12818616684165792775] = 1658561980214; b[12818616684165792775] = 1659061881205
a[9594788837974552645] = -9999999999801982; b[9594788837974552645] = -9999999999900991
a[10756418651392926596] = 1609192970168; b[10756418651392926596] = 1609692871159
a[15622342449324425858] = 1536061089124; b[15622342449324425858] = 1536560990115
a[8662469807681796974] = 1655574257340; b[8662469807681796974] = 1656074158331
a[7549491900148497689] = 1659718514805; b[7549491900148497689] = 1660218415796
a[12691716351984140582] = 1526963663472; b[12691716351984140582] = 1527463564463
a[6863230959130270198] = 334800396027; b[6863230959130270198] = 334800297018
a[10885488775109808482] = 404556237642; b[10885488775109808482] = 404556138633
a[2178850910632340753] = 1224174851393; b[2178850910632340753] = 1225174851393
a[15555711937382134455] = 1538159801815; b[15555711937382134455] = 1538659702806
a[853527863251661123] = 1591089405927; b[853527863251661123] = 1591589306918
a[15205258317333561497] = 1539161980366; b[15205258317333561497] = 1539661881357
a[5809349990080754322] = 1461507821625; b[5809349990080754322] = 1461507722616
a[15505467383917055354] = 1603688217912; b[15505467383917055354] = 1604188118903
a[4913750582093826587] = 401556732600; b[4913750582093826587] = 401556633591
a[8546346710767473316] = 1533561583994; b[8546346710767473316] = 1534061484985
a[14661372463477871655] = 1527963267501; b[14661372463477871655] = 1528463168492
a[9566915080051815704] = 1663741683386; b[9566915080051815704] = 1664241584377
a[16260793411010498693] = 1605001089037; b[16260793411010498693] = 1605500990028
a[16741098748880332286] = 1526412871203; b[16741098748880332286] = 1526912772194
a[1861553262909759721] = 1605673366167; b[1861553262909759721] = 1606173267158
a[619547416352742427] = 1654668910937; b[619547416352742427] = 1655168811928
a[9494067311732179131] = 623445940717; b[9494067311732179131] = 623445841708
a[1331377513055030482] = 1655083663293; b[1331377513055030482] = 1655583564284
a[6813566169204825397] = 1183993960484; b[6813566169204825397] = 1184493960484
a[7559236880452970335] = 408569306858; b[7559236880452970335] = 408569207849
a[18258054336678546872] = 1399787029817; b[18258054336678546872] = 1400286930808
a[16605820090421080764] = 1247938415807; b[16605820090421080764] = 1248438415807
a[183832415401159935] = 1529645544614; b[183832415401159935] = 1530645445605
a[7185925503841360543] = 331855247509; b[7185925503841360543] = 331855049491
a[16018934037271383860] = 1596136930618; b[16018934037271383860] = 1596636831609
a[9225466541780674347] = 1580587524767; b[9225466541780674347] = 1581087425758
a[11395463834478228815] = 1397394653477; b[11395463834478228815] = 1397894554468
a[12855817723964405877] = 1392656435566; b[12855817723964405877] = 1393156336557
a[14868861125384761818] = 1602684653341; b[14868861125384761818] = 1603184554332
a[12725565306498455722] = 1605660890921; b[12725565306498455722] = 1606160791912
a[6506839327377338710] = 1534013762310; b[6506839327377338710] = 1534513762310
a[16453926881535411425] = 1594561188034; b[16453926881535411425] = 1595061089025
a[8636595276350466451] = 624445346599; b[8636595276350466451] = 624445247590
a[8297342117955691749] = 1537913861402; b[8297342117955691749] = 1538413762393
a[16003289837583818697] = 1527413564288; b[16003289837583818697] = 1527913564288
a[2904563545748225697] = 631501485277; b[2904563545748225697] = 631501386268
a[5765376524396134055] = 1531061782105; b[5765376524396134055] = 1531561683096
a[5202832549098211959] = 1388045346545; b[5202832549098211959] = 1388545247536
a[5551728081135333369] = 1533165940656; b[5551728081135333369] = 1533665841647
a[11775900610622967344] = 1408606336476; b[11775900610622967344] = 1409106237467
a[12577917432507761736] = 1524904950337; b[12577917432507761736] = 1525404950337
a[14791690666447247393] = 1602630594137; b[14791690666447247393] = 1603130495128
a[2698939631194176774] = 1542056633680; b[2698939631194176774] = 1542556534671
a[14763246841156172877] = 1599085742539; b[14763246841156172877] = 1599585643530
a[8883267454474937136] = 1535571485134; b[8883267454474937136] = 1536071386125
a[12845880580091620532] = 1392371485134; b[12845880580091620532] = 1392871386125
a[17882005813995218741] = 1533963168312; b[17882005813995218741] = 1534463069303
a[13236246470225868516] = 1535071980101; b[13236246470225868516] = 1535571881092
a[536957898] = 647025544521; b[536957898] = 647525544521
a[18106556407344166019] = 1602074257393; b[18106556407344166019] = 1602574158384
a[3140790823164307049] = 1400436138611; b[3140790823164307049] = 1400936039602
```

Many of those balances are off by 5 LSK and some fee, which smells to me like the round finalization of the last round is not applied to mem_accounts.

### Which version(s) does this affect? (Environment, OS, etc...)

Betanet

**Comment by 4miners** [comment] 2018-05-27 22:55
@webmaster128 Thanks for the report, however it looks like duplicate of https://github.com/LiskHQ/lisk/issues/1949, which is already fixed in `beta.8`.

**Comment by webmaster128** [comment] 2018-05-28 06:46
Alright, thanks! Let’s wait for beta8 then

**Closed** 2018-05-28 06:47 UTC
