### ISSUE TITLE
Offset higher than count returns invalid data

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#1967] opened 2018-04-27 21:10 UTC
### Expected behavior
Any endpoint featuring limit and offset should not return any data when leaving data range with offset

### Actual behavior
It does return dummy accounts

### Steps to reproduce
Voters endpoint(it might affect others, didn't tested), browse with higher offset than current count.

### Which version(s) does this affect? (Environment, OS, etc...)
beta8, cbebff343f506124b0c05205246d19989c880a65

Example below, actual data ends at 3992.
 ```
}
  [3992]=>
  array(3) {
    ["balance"]=>
    string(10) "9900759988"
    ["publicKey"]=>
    string(64) "d444772dd2a7158899a122541c4be87f54d4e184c655c389fec554f0f8b932a9"
    ["address"]=>
    string(21) "15157009416924452424L"
  }
  [3993]=>
  array(4) {
    ["username"]=>
    NULL
    ["address"]=>
    string(21) "10848193573763399503L"
    ["publicKey"]=>
    string(0) ""
    ["balance"]=>
    string(13) "4054054054054"
  }
  [3994]=>
  array(4) {
    ["username"]=>
    NULL
    ["address"]=>
    string(21) "11551453712247444217L"
    ["publicKey"]=>
    string(0) ""
    ["balance"]=>
    string(13) "4054054054054"
  }
  [3995]=>
  array(4) {
    ["username"]=>
    NULL
    ["address"]=>
    string(21) "11551549432293832181L"
    ["publicKey"]=>
    string(0) ""
    ["balance"]=>
    string(13) "4054054054054"
  }
  [3996]=>
  array(4) {
    ["username"]=>
    NULL
    ["address"]=>
    string(21) "12743629913174781869L"
    ["publicKey"]=>
    string(0) ""
    ["balance"]=>
    string(13) "4054054054054"
  }
  [3997]=>
  array(4) {
    ["username"]=>
    NULL
    ["address"]=>
    string(21) "12906271186968955330L"
    ["publicKey"]=>
    string(0) ""
    ["balance"]=>
    string(13) "4054054054054"
  }
  [3998]=>
  array(4) {
    ["username"]=>
    NULL
    ["address"]=>
    string(21) "13252679007243273659L"
    ["publicKey"]=>
    string(0) ""
    ["balance"]=>
    string(13) "4054054054054"
  }
```

**Comment by nazarhussain** [comment] 2018-05-02 12:30
@karek314 Can you provide us more information on this issue. I can't understand which endpoint you are discussing here. And are you mentioning that we specify only offset and don't specify limit

I tried it on accounts endpoint and here is the output. 

```
➜  lisk ✗ curl localhost:4000/api/accounts?offset=102
{"meta":{"offset":102,"limit":10},"data":[{"address":"16313739661670634666L","unconfirmedBalance":"10000000000000000","balance":"10000000000000000","publicKey":"c094ebee7ec0c50ebee32918655e089f6e1a604b83bcaa760293c61e0f18ab6f","secondPublicKey":""}],"links":{}}
```

Can you provide the full request and response you used which generates the above data sample.

**Comment by karek314** [comment] 2018-05-03 16:35
This happened with -> `api/voters?publicKey=PK&limit=100&offset=$offset` when offset variable was accidentally higher than current count after iterating from 0 to max count.

I tried to reproduce this issue now, but i couldn't - it worked fine now.

**Comment by nazarhussain** [comment] 2018-05-04 15:30
Hi @karek314 I also can't reproduce this. I am closing this issue for now. If you came up with a scenario to reproduce this behavior again, please reopen this issue.

**Closed by nazarhussain** 2018-05-04 15:30 UTC
Labels: *medium, api, bug
