### ISSUE TITLE
System error { message: 'undefined is not a function'...

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#180] opened 2016-06-09 10:32 UTC
```
lisk_user@develop-desktop:~/lisk-main$ bash lisk.sh logs
     blockSignature: 'a1c22b553e495228ec43ee24b450d74c6512064fea5fdcd794cfa33ea8596f053aeb9aa175d9b7a7a8f82e85443d71e5da064733b099a6dfc77c6e48a8b03409',
     confirmations: NaN,
     totalForged: '200000000',
     transactions: [ [Object], [Object] ] } } 
fatal 2016-06-08 23:43:21 System error { message: 'undefined is not a function',
  stack: 'TypeError: undefined is not a function\n    at /home/lisk_user/lisk-main/app.js:3:9842\n    at /home/lisk_user/lisk-main/node_modules/async/lib/async.js:52:16\n    at Immediate.<anonymous> (/home/lisk_user/lisk-main/node_modules/async/lib/async.js:264:21)\n    at Immediate.<anonymous> (/home/lisk_user/lisk-main/node_modules/async/lib/async.js:44:16)\n    at Immediate.immediate._onImmediate (timers.js:418:16)\n    at processImmediate [as _immediateCallback] (timers.js:367:17)' }
info 2016-06-08 23:43:21 Cleaning up... 
info 2016-06-08 23:43:21 Cleaned up successfully 
error 2016-06-08 23:43:21 null 
error: Forever detected script exited with code: 1
```

I have noticed node went down during night.

**Comment by karek314** [comment] 2016-06-09 10:58
After restarting

```
info 2016-06-09 10:46:24 Rebuilding blockchain, current block height: 20000 
log 2016-06-09 10:46:25 GET /api/loader/status from 10.0.0.2 
log 2016-06-09 10:46:25 GET /api/loader/status from 10.0.0.2 
error 2016-06-09 10:46:34 { message: 'Maximum number of 101 votes exceeded (2 too many).',
  transaction: 
   { id: '5524930565698900323',
     height: 20407,
     blockId: '16820105418178921867',
     type: 3,
     timestamp: 238365,
     senderPublicKey: 'd09b5883f98350934345932d2e030e8478d2dba2985deaef85222cbc315d6421',
     requesterPublicKey: null,
     senderId: '6272272422739160383L',
     recipientId: '6272272422739160383L',
     amount: 0,
     fee: 100000000,
     signature: '18be11b3d5ce002b1f7866b01a87f02fb36ec9a95bf6eb53245b3fddee957c2e1f7618415e2ad02316c61c420bc9be7e3649104caa43d03579d3cbeba161430e',
     signSignature: 'bbfc43aa7fe7def729f4f73f3547f6e57a7a4776fc5a95169b309c5eb5f066e23c87017a12f095ce40c49d848ac1ff210a3c0383a6cf8c7df5f16302d6aa3107',
     signatures: null,
     confirmations: NaN,
     asset: { votes: [Object] } },
  block: 
   { id: '16820105418178921867',
     version: 0,
     timestamp: 238370,
     height: 20407,
     previousBlock: '4143114733638054568',
     numberOfTransactions: 2,
     totalAmount: 0,
     totalFee: 200000000,
     reward: 0,
     payloadLength: 3872,
     payloadHash: '3775d35d05c4c05b7d5063527e90e225d50c821ebd2b892787b75faa0b1cc110',
     generatorPublicKey: '2f872264534a1722e136bddf29a301fa97708f88583130770d54c1d11366e5fc',
     generatorId: '9926064757911337096L',
     blockSignature: 'a1c22b553e495228ec43ee24b450d74c6512064fea5fdcd794cfa33ea8596f053aeb9aa175d9b7a7a8f82e85443d71e5da064733b099a6dfc77c6e48a8b03409',
     confirmations: NaN,
     totalForged: '200000000',
     transactions: [ [Object], [Object] ] } } 
fatal 2016-06-09 10:46:34 System error { message: 'undefined is not a function',
  stack: 'TypeError: undefined is not a function\n    at /home/lisk_user/lisk-main/app.js:3:9842\n    at /home/lisk_user/lisk-main/node_modules/async/lib/async.js:52:16\n    at Immediate.<anonymous> (/home/lisk_user/lisk-main/node_modules/async/lib/async.js:264:21)\n    at Immediate.<anonymous> (/home/lisk_user/lisk-main/node_modules/async/lib/async.js:44:16)\n    at Immediate.immediate._onImmediate (timers.js:418:16)\n    at processImmediate [as _immediateCallback] (timers.js:367:17)' }
info 2016-06-09 10:46:34 Cleaning up... 
info 2016-06-09 10:46:34 Cleaned up successfully 
error 2016-06-09 10:46:34 null 
error: Forever detected script exited with code: 1
```

Seems like it's related to #160

**Comment by fix** [comment] 2016-08-30 10:33
Is this still an issue?

**Comment by karmacoma** [comment] 2016-09-18 23:37
Closing this issue, as not able to reproduce.

**Closed by karmacoma** 2016-09-18 23:37 UTC
Labels: bug
