### ISSUE TITLE
Approval should never be more than 100%

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk#782] opened 2017-09-11 07:16 UTC
Originally reported in Lisk Nano: https://github.com/LiskHQ/lisk-nano/issues/719 but to me, it looks like a backend issue.

### Expected behaviour
Would not expect Approval to ever be more than 100%
### Actual behaviour
I see on test net, approval for cc001 is at 100.49%. My guess is some math is incorrect. I am not familiar with that this is or how it's calculated.
![image](https://user-images.githubusercontent.com/5130533/30250490-70701c28-9679-11e7-8bf8-bcede3ab6c6b.png)

### Steps to reproduce
Log in to testnet and noticed the 1st person to vote for cc001 has over 100% Approval

**Comment by Isabello** [comment] 2017-09-11 08:37
Please provide the api used for this display so we can manually test it.

**Comment by slaweet** [comment] 2017-09-11 09:06
It's calling https://testnet.lisk.io/api/delegates/?offset=0&limit=100&q=

**Comment by Isabello** [comment] 2017-10-10 08:28
Closing as we cannot reproduce and code is sound, barring some database issue this cannot happen.

**Closed by Isabello** 2017-10-10 08:28 UTC
Labels: bug, easy
