### ISSUE TITLE
Terminate process when snapshot finished

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#2075] opened 2018-05-30 11:15 UTC
### Expected behavior
When running Node in snapshot mode `-s / --snapshot`, the process should terminate when a snapshot is finished.
### Actual behavior
After a snapshot is finished, Node continues to run. The current creating snapshots process relays on upper layer manager (like `lisk-scripts`) to kill the process:
https://github.com/LiskHQ/lisk-scripts/blob/295a03c8d1ec40572afd1989d4159998bf8f93ad/packaged/lisk_snapshot.sh#L182.
### Steps to reproduce
Run Node in a snapshot mode. Verify that the process exited when a snapshot was created. 
### Which version(s) does this affect? (Environment, OS, etc...)
*

**Comment by nazarhussain** [comment] 2018-05-30 11:21
@MaciejBaj Is it not the duplicate of https://github.com/LiskHQ/lisk/issues/2072

**Comment by nazarhussain** [comment] 2018-05-30 11:26
@4miners Yes I will debug it. The first assumption I can provide think is node terminate successfully but pm2 start it again. Will look into it and confirm the behavior.

**Comment by MaciejBaj** [comment] 2018-05-30 11:47
@nazarhussain I see the #2072 as a discussion, #2075 as a solution. The following PR should close both.

**Comment by nazarhussain** [comment] 2018-05-30 14:09
@MaciejBaj I confirmed this after snapshotting the process terminated successfully. 

```
[inf] 2018-05-30 13:23:27 | Snapshot creation finished
[inf] 2018-05-30 13:23:27 | Cleaning up...
[dbg] 2018-05-30 13:23:27 | Cache - Clean up database
[dbg] 2018-05-30 13:23:27 | Cache - Quit database
[dbg] 2018-05-30 13:23:27 | Export peers to database failed: Peers list empty
[inf] 2018-05-30 13:23:27 | Cleaned up successfully
```

See further details on https://github.com/LiskHQ/lisk/issues/2072#issuecomment-393162453. We can close the issue.

**Closed** 2018-06-19 14:38 UTC
Labels: *medium, bug, database
