### ISSUE TITLE
Launching the ICOconvert dapp from appstore crashes the whole node

### ISSUE THREAD

**Issue by TheGoldenEye** [LiskHQ/lisk#42] opened 2016-04-06 21:41 UTC
After launching the dapp the full node (not only the dapp) crashes. 
This is the last log:

```
{"level":"warn","message":"Main queue","timestamp":"2016-04-06 23:34:17","data":53}
{"level":"warn","message":"Main queue","timestamp":"2016-04-06 23:34:17","data":52}
{"level":"warn","message":"Main queue","timestamp":"2016-04-06 23:34:17","data":51}
{"level":"warn","message":"Main queue","timestamp":"2016-04-06 23:34:17","data":50}
{"level":"error","message":"loadUnconfirmedTransactions timer","timestamp":"2016-04-06 23:34:17","data":"Transaction already exists"}
{"level":"info","message":"Check blockchain on 181.28.143.243:7000","timestamp":"2016-04-06 23:34:19"}
{"level":"info","message":"Removing peer POST http://95.90.235.7:7000/peer/blocks","timestamp":"2016-04-06 23:34:20"}
{"level":"info","message":"Removing peer POST http://52.91.166.70:7000/peer/blocks","timestamp":"2016-04-06 23:34:20"}
{"level":"info","message":"Removing peer POST http://87.100.131.44:7000/peer/blocks","timestamp":"2016-04-06 23:34:20"}
{"level":"info","message":"Removing peer POST http://24.9.123.231:7000/peer/blocks","timestamp":"2016-04-06 23:34:20"}
{"level":"info","message":"Removing peer POST http://194.151.78.72:7000/peer/blocks","timestamp":"2016-04-06 23:34:20"}
{"level":"info","message":"Removing peer POST http://52.169.187.78:7000/peer/blocks","timestamp":"2016-04-06 23:34:20"}
{"level":"info","message":"Removing peer POST http://194.151.78.72:7000/peer/blocks","timestamp":"2016-04-06 23:34:20"}
{"level":"info","message":"Removing peer POST http://95.90.235.7:7000/peer/blocks","timestamp":"2016-04-06 23:34:24"}
{"level":"fatal","message":"Domain master","timestamp":"2016-04-06 23:34:28","data":{"message":"dapp is not defined","stack":"ReferenceError: dapp is not defined\n    at /opt/lisk/lisk-0.1.2-Linux-x86_64/app.js:7:1031\n    at /opt/lisk/lisk-0.1.2-Linux-x86_64/node_modules/async/lib/async.js:52:16\n    at iterate (/opt/lisk/lisk-0.1.2-Linux-x86_64/node_modules/async/lib/async.js:260:24)\n    at Object.async.forEachOfSeries.async.eachOfSeries (/opt/lisk/lisk-0.1.2-Linux-x86_64/node_modules/async/lib/async.js:281:9)\n    at Object.async.forEachSeries.async.eachSeries (/opt/lisk/lisk-0.1.2-Linux-x86_64/node_modules/async/lib/async.js:214:22)\n    at Object.B.launchApp (/opt/lisk/lisk-0.1.2-Linux-x86_64/app.js:7:606)\n    at /opt/lisk/lisk-0.1.2-Linux-x86_64/app.js:6:31259\n    at FSReqWrap.oncomplete (fs.js:95:15)"}}

```

**Comment by fix** [comment] 2016-08-30 10:18
Can you reproduce the issue with 0.3.2?

**Comment by TheGoldenEye** [comment] 2016-08-30 16:01
The ICOconvert app is unfortunately no longer available

**Comment by fix** [comment] 2016-08-30 16:10
true +1

**Comment by karmacoma** [comment] 2017-04-21 14:28
Closing due to: https://github.com/LiskHQ/lisk/issues/560

**Closed by karmacoma** 2017-04-21 14:28 UTC
Labels: bug
