### ISSUE TITLE
A peer can connect to itself on web socket layer with corrupted data

### ISSUE THREAD

**Issue by nazarhussain** [LiskHQ/lisk#1954] opened 2018-04-26 15:59 UTC
### Expected behavior
A peer shouldn't be able to connect to its own self. The connection request must be rejected during handshake process.

### Actual behavior
Currently, a peer can connect to itself but with corrupted data. During integration tests found that peer connected to itself and then banned.

On `GET /api/peers` it appears like this

```
        {
            "ip": "127.0.0.1",
            "wsPort": 35608,
            "state": 1,
            "os": "debian",
            "version": "0.0.1",
            "broadhash": "198f2b61a8eb95fbeed58b8216780b68f697f26b849acf00c8c93bb9b24f783d",
            "height": 1,
            "nonce": "xKuEybs16XIHFoHA",
            "httpPort": 35609
        },
```

### Steps to reproduce
1. Run the integration tests and when nodes are up 
2. Call `curl http://127.0.0.1:4000/api/peers` 
3. The list must contain 9 peers but you will find 10

### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by ManuGowda** [comment] 2018-05-04 13:55
@nazarhussain The peer which you listed in the issue is a valid peer from integration test
```
describe('when functional tests are successfully executed against 127.0.0.1:5000', () => {
						before(done => {
							setup.shell.runMochaTests(
								[
									'test/functional/http/get/peers.js',
									'test/functional/http/get/blocks.js',
									'test/functional/http/get/transactions.js',
								],
								done
							);
						});
```
we are running functional test inside the integration test, in the `test/functional/http/get/peers.js` test we are creating a peer using a random `wsPort` and `httpPort` this is the reason why we see that random peer while running integration test. So I am closing this issue as its no longer valid.

**Closed by ManuGowda** 2018-05-04 13:55 UTC
Labels: *hard, bug, transport
