### ISSUE TITLE
Build internal api calls rate limiting by source IP 

### ISSUE THREAD

**Issue by Gr33nDrag0n69** [LiskHQ/lisk#481] opened 2017-03-16 23:22 UTC
Maybe exist already or something in the bakclog, honestly didn't check.

Like title said, Build internal api calls rate limiting by source IP 

Last 48 hours proved that this kind of "built in" mitigation is necesssary

Rate-limit by IP could also  be dynamic, if possible without too much ressources (CPU/RAM) needed.

- "max api calls (any IP) / sec" variable (let say X)
- "max api calls (single IP) / sec" variable (let say Y)
- "min api calls (single IP) / sec" variable (let say Z)

so when usage is low, a single IP can make up to Y api call sec
but when usage is higher the limit decrease until it reach Z

There is always the X global limit that when passed connections are just dropped

X Y Z could be configurable so they can be adjusted to the host server 
CPU/Memory being target once bandwidth ddos protection is in place

**Comment by 4miners** [comment] 2017-03-17 00:16
There is already basic limit implemented (settings available in `config.json`), but I'm not really sure if it's works as intended - we will investigate.

**Comment by Gr33nDrag0n69** [comment] 2017-03-17 00:24
I think that the concept of global limit rate vs limit rate by ip isn't there (using both)
so far in the softwares I've built,  it always gave me good result

**Comment by Gr33nDrag0n69** [comment] 2017-03-30 23:53
another attack came today on public open api nodes

The source is the same as on ark 1 week ago and lisk 2 weeks ago.

Since we can't force end-user to configure properly their firewall, I think that this whole class C should be blacklisted in lisk next release config.json

185.166.239.0/24

**Comment by realhagie** [comment] 2017-03-31 07:13
How about using it's own port for API calls? The complete control could than be put on another layer into iptables. I proposed that months ago like to have api calls on a complete different "channel"

**Comment by 4miners** [comment] 2017-03-31 12:06
@Gr33nDrag0n69 That will not happen, node operators should be responsible for maintain and secure their nodes. We cannot just keep adding more and more bans in every release. What if the next attack will be from OVH/Vultr class where delegates have their nodes?

@realhagie There is already plan to implement it.

**Comment by karek314** [comment] 2017-03-31 13:13
How about allowing nodes use of domain instead of public ip (if defined and configured) so service like Cloudflare can be used and completely hide behind cloudflare, then layer 7 attacks can be defended similar way i did [here ->https://github.com/karek314/ddos-deflate-nginx-cloudflare](https://github.com/karek314/ddos-deflate-nginx-cloudflare) while other layers are protected by cloudflare.

Of course i'm not encouraging entire network to hide behind cloduflare since it would centralise things too much, however some portion of networking running behind cloudflare could be some "safe heaven" if massive ddos happens. Not even saying about additional caching advantages.

**Comment by Gr33nDrag0n69** [comment] 2017-03-31 22:03
I understand about config.json blacklist. was just an idea

The thing is vultr and ovh ips are traceable and theses companies are serious and close customer vms when source of attack are reported, this wasn'T the case with yesterday'S class c. I know, I checked to report them.

**Comment by diego-G** [comment] 2018-09-04 13:13
After migrating our API to Swagger, we have some default limits you can check out in here https://github.com/LiskHQ/lisk/blob/8f7de3963eaa48a6e2d8b081de37921b85911a53/api/fittings/lisk_request_limit.js#L22-L27.
I will close this issue. @Gr33nDrag0n69 if you need us to modify them or add another, please let us know.

**Closed by diego-G** 2018-09-04 13:13 UTC
Labels: *hard, api
