### ISSUE TITLE
top-level updates missing a transaction

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1291] opened 2018-01-12 15:40 UTC
https://github.com/LiskHQ/lisk/blob/cbf9f58d7a82413e3d0849b885a91d16de80c83c/logic/round.js#L114

This whole block needs to be inside a transaction, as it is doing a series of updates that currently happen against the top-level database object instead, compromising both performance and integrity.

i.e. this:

```js
return self.scope.library.db.rounds.updateVotes(...
```

probably should be:

```js
return self.t.rounds.updateVotes(...
```

in order to use the right connection context.

**Comment by karmacoma** [comment] 2018-01-12 16:26
We have this in mind already I think. Please see task list outlined in #302, the last item to do covers the inclusion of rounds within a top-level database transaction (`saveBlock`).

**Comment by karmacoma** [comment] 2018-01-12 21:12
Duplicate of: #1297

**Closed by karmacoma** 2018-01-12 21:12 UTC
