### ISSUE TITLE
config.json gets overwritten when different genesis block is applied

### ISSUE THREAD

**Issue by MaciejBaj** [LiskHQ/lisk#1942] opened 2018-04-26 07:49 UTC
### Expected behavior
The config file should not be overwritten
### Actual behavior
config file gets overwritten once application exits.
### Steps to reproduce
_To be investigated further_
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by SargeKhan** [comment] 2018-04-26 09:42
I have tried loading mainet genesis block with testnet config.json file, testnet genesis block with mainnet config.json file. I've also tried changing values in config.json file and restarting the application to see if the config file gets overwritten or not. But I've been unable to reproduce this issue. We [update config.json](https://github.com/LiskHQ/lisk/blob/0.9.14/app.js#L214) in 0.9.* versions, but this does not happen anymore in 1.0.0. So, closing this issue since it seems to not exist anymore.

**Closed** 2018-04-26 09:42 UTC
Labels: *medium, bug
