### ISSUE TITLE
dapp system error { message: 'undefined is not a function'... Dapp can't download blocks from delegate node

### ISSUE THREAD

**Issue by karek314** [LiskHQ/lisk#28] opened 2016-04-03 14:15 UTC
Im running node with dapp from guestBook example. Which actually does not work, everything is fine locally, but when i tried to use dapp from different node it couldn't fetch blockchain

Anyone can install dapp currently on testnet -> http://localhost:7000/dapp/8565618818751641866
And reproduce issue.

```
dapp loading process pid 1930

Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js: 

dapp loaded process pid 1930

Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js: 

blocks 1
current 0

Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js: 

blockchain loaded

info 2016-04-03 10:10:53 Check blockchain on 188.166.161.239:7000 
Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js: 

found blocks at 89.69.168.15:7000

Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js: 

load blocks after 1

incoming 37534 bytes
info 2016-04-03 10:10:56 Removing peer POST http://194.151.78.72:7000/peer/blocks 
info 2016-04-03 10:10:57 Removing peer POST http://109.153.180.57:7000/peer/transactions 
info 2016-04-03 10:10:57 Removing peer POST http://194.151.78.72:7000/peer/transactions 
info 2016-04-03 10:10:57 Removing peer POST http://194.151.78.72:7000/peer/transactions 
info 2016-04-03 10:10:57 Removing peer POST http://40.79.47.203:7000/peer/transactions 
log 2016-04-03 10:10:59 Recieved new block id: 2688780107953700387 height: 430847 slot: 3115506 reward: 500000000 
log 2016-04-03 10:10:59 Recieved new block id: 2688780107953700387 height: 430847 slot: 3115506 reward: 500000000 
log 2016-04-03 10:11:00 Recieved new block id: 2688780107953700387 height: 430847 slot: 3115506 reward: 500000000 
Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js: 

loop skip slot

Debug /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/index.js: 

dapp system error { message: 'undefined is not a function',
  stack: 'TypeError: undefined is not a function\n    at Object.private.addAccount (/root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/modules/blockchain/accounts.js:74:30)\n    at Accounts.setAccountAndGet (/root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/modules/blockchain/accounts.js:168:21)\n    at Transactions.applyUnconfirmedTransaction (/root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/modules/blockchain/transactions.js:130:30)\n    at /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/modules/blockchain/blocks.js:507:36\n    at /root/lisk-0.1.2-Linux-x86_64/dapps/8565618818751641866/node_modules/z-schema/src/Report.js:45:13\n    at process._tickDomainCallback (node.js:381:11)' }
```

**Comment by fix** [comment] 2016-08-30 10:19
is this reproduced with 0.3.2

**Comment by karmacoma** [comment] 2017-04-21 14:27
Closing due to: https://github.com/LiskHQ/lisk/issues/560

**Closed by karmacoma** 2017-04-21 14:27 UTC
Labels: bug
