### ISSUE TITLE
PUT /api/multisignatures not working?

### ISSUE THREAD

**Issue by mongrim** [LiskHQ/lisk#237] opened 2016-07-12 11:10 UTC
I want to create delayed transactions via API.
As I understand from docs, currently it should be available by using multi-signature transactions.

However, when I try to create a multi-sig account via API, I get same error every time:
`{"success":false,"error":"Invalid transaction asset: 12803541398492998618"}`

Am i doing something wrong?

**Comment by fix** [comment] 2016-07-13 13:59
what do you mean a delayed transaction?

As for multi-sig, there is an issue preventing from creation of multi-signature, fixed in next version 0.4.0

**Comment by mongrim** [comment] 2016-07-13 14:44
Thank you for the answer.

I need to know transaction id before it is sent to network so I can trace it if something went wrong (i.e. lost connection to lisk). If you can add dedicated api call for this purpose, it would be great - multi-sig accounts don't look like a best way to do it.

Can you provide any ETA on when the next version will be released?

**Comment by fix** [comment] 2016-07-13 14:50
Are you using lisk-js? https://www.npmjs.com/package/lisk-js

**Comment by mongrim** [comment] 2016-07-13 15:07
No, I'm experimenting with just lisk client and its http api. My application is written in another language, and I was not going to use javascript here.

**Comment by fix** [comment] 2016-07-13 15:18
Which language? I do not advise using api to create transaction.
Reproducing lisk-js in your language might not be difficult.

**Comment by ByronAP** [comment] 2016-07-15 12:46
When you send a transaction (type doesn't matter) it will return a transaction id on success. You can use this to track the transaction and see how it progresses from unconfirmed to being confirmed and on the chain. if you receive an error response it didn't go through. If you don't receive a response at all then you have bigger issues.

**Comment by mongrim** [comment] 2016-07-15 20:05
> Which language? I do not advise using api to create transaction. Reproducing lisk-js in your language might not be difficult.

Ok, you are right, it was easy enough to implement minimum required functions in python. Thanks for the advise. Are there any plans on improving your API so it is safe to use it without porting your libraries to other languages? It would be much more convenient for integration with your blockchain..


>  If you don't receive a response at all then you have bigger issues.
Okay, and in this case of 'bigger issues' i won't have proper means to analyse, did I send money or not? No, thanks. That's too risky.

**Comment by ByronAP** [comment] 2016-07-15 20:38
If you are running a node and interacting with it via api and you don't get a response then yes you have bigger issues since if you are using the api to control lisk you should be calling the api from the same machine using loop back. Which can only mean that either the lisk node is not running or something is totally off. There is virtually no risk of sending a transaction and not getting a response. In the off chance (has never happened to me) that you don't get a response shut down withdrawals aND have your system check recent transactions in the wallet for one that matches the request and if that doesn't produce a reliable result look at the transactions manually to check if it was sent. But more importantly find out why it was not sent.

**Comment by ByronAP** [comment] 2016-07-15 20:44
If this did not work reliably us exchanges would have major problems. Which we don't. I've had more issues with eth api reliability than lisk by a lot.

**Comment by mongrim** [comment] 2016-07-21 12:41
Even if it works reliably today, you can not guarantee, that it would still work tomorrow. Better safe, than sorry.
Of course, if something went off, finding out the reason is the first thing to do. But blocking withdrawals in the meantime is not a good option. Why should your users suffer because you are not sure if you sent something to blockchain or not?

**Comment by ByronAP** [comment] 2016-07-21 12:51
Because if you don't you are potentially exposing yourself to a loss of users funds. The minor risk of down time doesn't outweigh the benefits.

**Comment by mongrim** [comment] 2016-07-21 13:05
Exactly. But with extra step you don't really expose yourself to anything. Your code can do most of the checks automatically and you can sleep peacefully.

**Comment by karmacoma** [comment] 2016-07-28 08:45
Issue has been resolved for https://github.com/LiskHQ/lisk/milestone/3.

**Closed by karmacoma** 2016-07-28 08:45 UTC
Labels: bug
