### ISSUE TITLE
When setting log level to trace, one log entry is not parsed correctly.

### ISSUE THREAD

**Issue by yairlisk** [LiskHQ/lisk#1755] opened 2018-03-19 14:38 UTC
### Expected behavior
Logs should be clear and well parsed, no need to send log entry that are not readable.

### Actual behavior
i see this trace log every round:
[dbg] 2018-03-19 14:30:09 | Performing forward tick
**[trc] 2018-03-19 14:30:09 | [object Object]**
### Steps to reproduce
start a lisk node, enable trace logs to file and check the logs.

### Which version(s) does this affect? (Environment, OS, etc...)
version 1.0.0
OS Ubuntu 
Devnet

**Comment by ManuGowda** [comment] 2018-03-20 16:25
@yairlisk I couldn't reproduce the issue on dev machine, here is the log with `trace` enabled.
```
[dbg] 2018-03-20 16:23:09 | Performing forward tick
[trc] 2018-03-20 16:23:09 | { library:
   { logger:
      { setLevel: [Function],
        none: [Function: log],
        trace: [Function: log],
        debug: [Function: log],
        log: [Function: log],
        info: [Function: log],
        warn: [Function: log],
        error: [Function: log],
        fatal: [Function: log] },
     db:
      Database {
        connect: [Function],
```

for now, I am closing this issue.

**Closed by ManuGowda** 2018-03-20 16:25 UTC
Labels: *easy, bug
