### ISSUE TITLE
API - Search for votes randomly fails and returns a wrong error message

### ISSUE THREAD

**Issue by osvaldovega** [LiskHQ/lisk#3145] opened 2019-03-21 16:46 UTC
### Expected behavior
When the app execute this call **api/votes?address=3453453453455L&limit=101&offset=0**, should return a correct value or in case of error return the error with more details, or at least making reference to the votes search and not to delegates.

### Actual behavior

In the Hub app, when we try to search for an account, one of the steps for get all account details is the search for account votes, for get this information we call the endpoint **api/votes?address=3453453453455L&limit=101&offset=0**, sometimes fails and some other just pass correctly.

I made several tests to identify what could be the problem but no luck, after check the problem with @SargeKhan he noticed that the way the endpoint was implemented it is not right for when it fails.

Here are some screenshots of the error message.

<img width="906" alt="Screen Shot 2019-03-21 at 17 05 41" src="https://user-images.githubusercontent.com/11184770/54767891-6896cb00-4bfe-11e9-8fd1-d105b2afa354.png">
<img width="904" alt="Screen Shot 2019-03-21 at 17 06 02" src="https://user-images.githubusercontent.com/11184770/54767895-6af92500-4bfe-11e9-9fbf-4c00e1fbcf42.png">
<img width="717" alt="Screen Shot 2019-03-21 at 17 06 14" src="https://user-images.githubusercontent.com/11184770/54767908-6f254280-4bfe-11e9-9d4b-f446eb3cffd8.png">

In the other hand if I try to search for the same information using postman return data in the correct way like this.

<img width="967" alt="Screen Shot 2019-03-21 at 17 09 37" src="https://user-images.githubusercontent.com/11184770/54767912-71879c80-4bfe-11e9-8f33-6e2f172b2703.png">

### Steps to reproduce

1- Login to the Lisk Hub app.
2- Go to Wallet and do a click on the send lisks
3- type any random address and amount.
4- do a click in the Go to confirmation button and in the confirmation page do click in the send button.
5- In the final screen you need to check the browser console where you can find the error message and in the network tab the details of the call.

![Votes error](https://user-images.githubusercontent.com/11184770/54768910-82391200-4c00-11e9-8679-34150af7a341.gif)

### Which version(s) does this affect? (Environment, OS, etc...)

You can use the last Lisk Hub version for this test and for the Lisk Core I am using version 1.5.0-alpha.5 running it on Docker

<img width="435" alt="Screen Shot 2019-03-21 at 17 42 44" src="https://user-images.githubusercontent.com/11184770/54769049-bf050900-4c00-11e9-848e-6fdc1ae71ffe.png">

**NOTES:**

Looks like always fails the first time that you call the function and after that all other calls work fine.
You can use any random address the error it is not related to an specific address.

**Comment by limiaspasdaniel** [comment] 2019-04-03 08:19
This is happening only when posting a transaction with non-existent accounts that need to first be created in the database. Therefore, calling `/api/votes` before the account has been created causes the API to report that it can't retrieve vote info for this account, so it's not a bug. This can be solved in the frontend side by checking if the account exists first.

I will close this issue and thanks @osvaldovega for clarifying issue description.

**Closed** 2019-04-03 08:19 UTC
Labels: api, bug
