### ISSUE TITLE
Inconsistencies in mem_accounts table management

### ISSUE THREAD

**Issue by 4miners** [LiskHQ/lisk#1562] opened 2018-02-14 07:38 UTC
### Expected behavior
Table `mem_accounts` should be maintained same way as on `master` branch.
### Actual behavior
There are some differences, for example:

After genesis block insertion:
- for delegates field `u_username` is set to `NULL` istead of delegate name
- for delegates field `u_isDelegate` is set to `0` instead of `1`
- after forging a block field `producedblocks` is not updated for delegate that forged that block

These are only brief observations, there can be more.

### Steps to reproduce
Run app, wait for genesis block insertion, wait for some blocks, check `mem_accounts`
### Which version(s) does this affect? (Environment, OS, etc...)
1.0.0

**Comment by 4miners** [comment] 2018-02-14 14:47
Issue with `u_username` and `u_isDelegate` is fixed with `0.9.12`, thanks @nazarhussain for your research on it. 👍

**Comment by nazarhussain** [comment] 2018-02-14 14:53
Verified the behavior. The root cause of the problem is in applying confirmed state of `delegate` type transaction; 

https://github.com/LiskHQ/lisk/blob/b4f91e0312d71a7b39e7ac0d4214cdba81d33ec0/logic/delegate.js#L278-L286

This issue is fixed in `0.9.12` with the commit https://github.com/LiskHQ/lisk/commit/1d8e9c3980ed1a686fd2d31e7a6ccb4ba86b67e4

**Comment by karmacoma** [comment] 2018-02-14 14:57
Thanks @nazarhussain @4miners

**Comment by 4miners** [comment] 2018-02-14 14:58
Wait @karmacoma , there is still issue with `producedblocks`.

**Comment by nazarhussain** [comment] 2018-02-14 15:26
The problem with `produced blocks` the inconsistency of the attribute name case in code and in model definition. 

https://github.com/LiskHQ/lisk/blob/b4f91e0312d71a7b39e7ac0d4214cdba81d33ec0/logic/round.js#L99

https://github.com/LiskHQ/lisk/blob/1.0.0/logic/account.js#L805

Since we are incrementing these attributes with a static sql, which don't convert the name cases. If we do general update for account that handles the case conversion. Same applies to missed blocks as well. 

Better approach to fix it permanently is to write a migration to change column names as what is specified mostly around the code. Also catch and throw the error here. 

https://github.com/LiskHQ/lisk/blob/b4f91e0312d71a7b39e7ac0d4214cdba81d33ec0/logic/account.js#L482-L484

**Comment by nazarhussain** [comment] 2018-02-14 15:37
@MaciejBaj Probably we should add this test scenario in integration tests. To check if the delegate who had forged the block, should have increment `producedBlocks` count.

**Comment by 4miners** [comment] 2018-02-14 15:41
@nazarhussain Test for that will come with https://github.com/LiskHQ/lisk/issues/1303, already have them.

**Closed** 2018-02-15 12:01 UTC
Labels: bug, database
