### ISSUE TITLE
Live Lisk API docs

### ISSUE THREAD

**Issue by slaweet** [LiskHQ/lisk#526] opened 2017-04-05 13:56 UTC
## Current behaviour
When I go to
https://login.lisk.io/api/

I get `Cannot GET /api/`

## Expected behaviour

I want to get Index page for Lisk API documentation that lists all the available APIs.
Something like what we had in my past project:
https://outlinemaps.org/flashcards/
The page lists all endpoints and you can click any of them and get e.g.:
https://outlinemaps.org/flashcards/contexts?html=True
which is HTML version with all documentation of one particular JSON API endpoint. You can get the JSON just by removing the `?html=True`:
https://outlinemaps.org/flashcards/contexts

It's also very handy from the other side when I'm working on some code that uses the JSON call and need to check something in the documentation. I can just add `?html=True` and voila: I get what I need.

It's all automatically generated from the documentation comments in the code with use of some decorators.

**Comment by karmacoma** [comment] 2017-04-21 14:51
Closing as duplicate of: #240

**Closed by karmacoma** 2017-04-21 14:51 UTC
Labels: duplicate
