### ISSUE TITLE
Fix intermittent test failures for dapps ordering

### ISSUE THREAD

**Issue by diego-G** [LiskHQ/lisk#971] opened 2017-11-15 14:57 UTC
## Expected behavior

Application should return always the correct requested ordering response for GET `/api/dapps?orderBy=` endpoint. There are some test cases addressing this functionality.

## Actual behavior

https://jenkins.lisk.io/job/lisk-core/view/change-requests/job/PR-953/36/

## Steps to reproduce:

It reproduces randomly in Jenkins.

**Comment by karmacoma** [comment] 2017-11-18 19:37
Duplicate of: #977

**Closed by karmacoma** 2017-11-18 19:37 UTC
Labels: duplicate
