### ISSUE TITLE
Improve process exit

### ISSUE THREAD

**Issue by vitaly-t** [LiskHQ/lisk#1788] opened 2018-03-26 15:04 UTC
### Expected behavior

When the application encounters a critical error that requires the process shut down, it must invoke an internal code block that will process the error and invoke `process.exit(value)` in the end with correct exit code.

This will let the hosting process know which re-spawning strategy needs to be executed:

* Immediate process restart
* Delayed process re-start
* Restart with a back-up configuration
* Machine restart
* Etc,...combinations

### Actual behavior

Use of `process.exit` is all over the place, and the hosting process does not know what is going on, and what should be done when the process dies.

### Steps to reproduce

Any step that will hit one of those `process.exit` calls, of which there are plenty.

### Which version(s) does this affect? (Environment, OS, etc...)

All.

**Comment by jondubois** [comment] 2018-07-13 13:40
I think that we should introduce additional exit codes and behaviours on an as-needed basis. Right now we have two exit codes: `0` for an intentional process exit and `1` for an unintentional process exit caused by a fatal error; in both of these cases, the current behaviour is to immediately respawn the affected process.

This immediate respawn behaviour ensures that the main priority of any process within the Lisk node is to resume its job as soon as possible after a crash - This is often the desired behaviour; especially if the crash was an unusual one-off occurrence. The main downside is that in some scenarios, it can make the logs look bad (I.e. it can spam the logs if a process crashes repeatedly in quick succession).

In the case of the database server not being available, I think that an additional, separate exit code for 'Delayed process re-start' makes sense in terms of reducing the log spam - Adding a delay in this case means that the affected process will incur a few additional seconds of downtime before it resumes its job but this additional delay may be worth it in terms of reducing log spam.

For a Lisk node, I can't think of a use case for a separate 'Restart with a back-up configuration', 'Machine restart' or combinations of error codes. I think that we should handle different error codes in the simplest way possible from a central place.

I agree that there are too many `process.exit(code)` all over the place; the decision to shut down a process should be made in a central place.

**Comment by vitaly-t** [comment] 2018-07-13 14:07
There should be a generic crash handler, one that logs the crash with all details, before exiting the process.

i.e. `process.on('error', handler)` or something ;)

**Comment by SargeKhan** [comment] 2018-07-23 13:56
In the case of snapshotting, when the snapshot finishes successfully node fires `cleanup` event. Which always exits with error code 1. This is not a valid behavior and should be fixed as part of this issue.

**Closed** 2018-08-08 16:06 UTC
Labels: :hammer:  reliability, app, standards
